services:
  nginx_alice:
    image: nginx:1.25.4-alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf/
  ngrok_alice:
    image: ngrok/ngrok:latest
    ports:
      - "4041:4040"
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./ngrok/ngrok.yml:/etc/ngrok.yml
    depends_on:
      - nginx_alice
    env_file:
      - ./.env
  redis_alice:
    image: redis:7.2.4-alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_storage:/var/lib/redis/data/
  bot_alice:
    image: potesuch/alicestation-bot
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - redis_alice
      - ngrok_alice
    env_file:
      - ./.env

volumes:
  redis_storage:
